### ISSUE TITLE
Div optional?

### ISSUE THREAD

**Issue by atrauzzi** [jaredpalmer/react-simple-infinite-scroll#2]
Would love to be able to have the `div` as optional.  Then I could use this in a component that provides its own container elements (tbody).

**Comment by pgarciacamou** [comment]
@atrauzzi I see what you are trying to do and I believe it could be useful. The main goal would be to try to keep the implementation *simple* as stated in the name of the repo.

The first idea I had is to just pass a prop (e.g. `isSelfContained`) which would tell the render method to either return the container or a `React.Fragment`, the problem with this approach is that I believe is very short-sighted.

The other idea I had, which I believe is more powerful/flexible is to introduce `props.render` and `props.component` (common react practice adopted after `react-router`) and then use `React.Fragment`, which will still keep the implementation *simple* enough for me. The problem is that to do this I had to update the dependencies and it threw some typescript errors, and I do not know any typescript ¯\_(ツ)_/¯.

Here was what I was trying to do:

*Note: I omitted most of the code to make this short.*

```jsx
import * as React from 'react';

export interface InfiniteScrollProps {
  render?: () => void;
  component?: any;
}

export class InfiniteScroll extends React.Component<InfiniteScrollProps, {}> {
  render() {
    const fragment = (
      <React.Fragment>
        {this.props.children}
        <div ref={i => this.sentinel = i} />
      </React.Fragment>
    );

    if(this.props.render) {
      return this.props.render({ children: fragment });
    }

    const Element = this.props.component || React.createElement("div");

    return <Element>{fragment}</Element>;
  }
}

export default React.createFactory(InfiniteScroll);
```

@jaredpalmer what do you think?

Some comments:

1. we should also think about the possibility of removing `React.createFactory` as it is considered legacy.
2. I do not know if anything else than `const` can be used in typescript to specify a React Element (same goes for `props.component`).

**Comment by pgarciacamou** [comment]
I just had another idea that might not need updating dependencies:

```
import * as React from 'react';

export interface InfiniteScrollProps {
  render?: () => void;
  component?: any; // some Element type in typescript
}

export class InfiniteScroll extends React.Component<InfiniteScrollProps, {}> {
  render() {
    const sentinel = <div ref={i => this.sentinel = i} />;

    if(this.props.render) {
      return this.props.render({
        sentinel,
        children: this.props.children
      });
    }

    if(this.props.component) {
      const Element = this.props.component;
      return (
        <Element sentinel={sentinel}>
          {this.props.children}
        </Element>
      );
    }

    return (
      <div>
        {this.props.children}
        {sentinel}
      </div>
    );
  }
}

export default React.createFactory(InfiniteScroll);
```

Examples:

```jsx
const withRender = (
  <InfiniteScroll
    render={(props) => (
      <section>
        {props.children}
        {props.sentinel}
      </section>
    )}
  />
);

const MyComponent = (props) => (
  <section>
    {props.children}
    {props.sentinel}
  </section>
);

const withComponent = (
  <InfiniteScroll component={MyComponent} />
);

const original = (
  <InfiniteScroll>
    <div>Hello</div>
  </InfiniteScroll>
);
```

**Comment by pgarciacamou** [comment]
@atrauzzi I created #3 if you want to add your comments.
